# 系统接口端口号及地址
server:
  port: 8888
  servlet:
    context-path: "/blog/api"

spring:
  # Mysql数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  # Redis数据库配置
  redis:
    port: 6379
    host: localhost
    database: 0

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: false

# 七牛云配置
qiniu:
    domain: http://q85tncpu6.bkt.clouddn.com
    access-key: FA2GnJW8vQrfb9QeutuiNl4w4qPrjYDvpquLDhyK
    secret-key: ESOjdYhQ_oZd-VIhRp4u_cj0R9nCHPhMdNbE7IuZ
    bucket: free-blog-api